### ISSUE TITLE
Ext namespace

### ISSUE THREAD

**Issue by naajaw** [sencha/ext-react-cra-eject#1]
I followed these instructions which got everything working perfectly until I ran into needing to create a store via `Ext.create()`, which I tried throwing in a `store` variable within one of my components (exactly how every example component does in the Ext React Kitchen Sink source), but it doesn't compile because `Ext` is not defined.

Tried the same thing in this repo; same problem:

```
Failed to compile.

./src/App.js
  Line 8:  'Ext' is not defined  no-undef
```

For context, here's my `src/App.js`. For simplicity, I just wrote `Ext.create()` since the problem is only related to the `Ext` reference.

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import { Grid, Column } from '@extjs/ext-react';

class App extends Component {

  store = Ext.create();

  render() { /* unchanged */ }
}

export default App;
```

I've looked at a lot of files and repos everywhere, all of them seem to just pull Ext out of thin air and it works. Is there another step to get access to Ext?

I'm using Node v8.2.1 and npm v5.3.0

**Comment by markbrocato** [comment]
Thank you for pointing that out.  This can be fixed by adding Ext as a global to the ESLint config.  That step is described in the updated readme:

https://github.com/sencha/ext-react-cra-eject#8-add-ext-as-a-global-to-the-eslint-config

I've also updated package.json to reflect this change.
